version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
